version: "3"
services:
  redis:
    container_name: quad-redis
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: redis-server --requirepass quad3
    volumes:
      - "$PWD/dockerdata/redis:/data/redis"
